-- Autogenerated by MSIL2Ada
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
package dotnetgraphlibrary is
   pragma Preelaborate;
end dotnetgraphlibrary;
pragma Import(MSIL,dotnetgraphlibrary,
   "[dotnetgraph]dotnetgraphlibrary");
