-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
limited with MSSyst.String;
limited with MSSyst.Type_k;
limited with numbers.value;
package raptor.Value_2D_Array is
   type Typ is new MSSyst.Object.Typ   with record
      null;
   end record;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function new_Value_2D_Array(
      This : Ref := null) return Ref;
   function get_Doubleaa(
      This : access Typ) return MSIL_Types.Float64_Array_Array;
   function get_Int32aa(
      This : access Typ) return MSIL_Types.Int32_Array_Array;
   function get_Singleaa(
      This : access Typ) return MSIL_Types.Float32_Array_Array;
   function Get_Value(
      This : access Typ;
      value_index1 : access numbers.value.Typ'Class;
      value_index2 : access numbers.value.Typ'Class) return access numbers.value.Typ'Class;
   procedure set_Doubleaa(
      This : access Typ;
      values : MSIL_Types.Float64_Array_Array);
   procedure set_Int32aa(
      This : access Typ;
      values : MSIL_Types.Int32_Array_Array);
   procedure set_Singleaa(
      This : access Typ;
      values : MSIL_Types.Float32_Array_Array);
   procedure Set_Value(
      This : access Typ;
      value_index1 : access numbers.value.Typ'Class;
      value_index2 : access numbers.value.Typ'Class;
      v : access numbers.value.Typ'Class);
private
   pragma Convention(MSIL,Typ);
   pragma MSIL_Constructor(new_Value_2D_Array);
   pragma Import(MSIL,get_Doubleaa,"get_Doubleaa");
   pragma Import(MSIL,get_Int32aa,"get_Int32aa");
   pragma Import(MSIL,get_Singleaa,"get_Singleaa");
   pragma Import(MSIL,Get_Value,"Get_Value");
   pragma Import(MSIL,set_Doubleaa,"set_Doubleaa");
   pragma Import(MSIL,set_Int32aa,"set_Int32aa");
   pragma Import(MSIL,set_Singleaa,"set_Singleaa");
   pragma Import(MSIL,Set_Value,"Set_Value");
end raptor.Value_2D_Array;
pragma Import(MSIL,raptor.Value_2D_Array,
   ".ver 4:0:5:2",
   "[raptor]raptor.Value_2D_Array");
