-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
limited with MSSyst.ComponentModel.CancelEventHandler;
with MSSyst.ComponentModel.Component;
with MSSyst.ComponentModel.IComponent;
limited with MSSyst.ComponentModel.IContainer;
limited with MSSyst.ComponentModel.ISite;
with MSSyst.ComponentModel.ISynchronizeInvoke;
limited with MSSyst.Delegate;
limited with MSSyst.Drawing.Bitmap;
limited with MSSyst.Drawing.Color;
limited with MSSyst.Drawing.Font;
limited with MSSyst.Drawing.Graphics;
limited with MSSyst.Drawing.Icon;
limited with MSSyst.Drawing.Image;
limited with MSSyst.Drawing.Point;
limited with MSSyst.Drawing.Printing.PrintPageEventArgs;
limited with MSSyst.Drawing.Rectangle;
limited with MSSyst.Drawing.Region;
limited with MSSyst.Drawing.SizeF;
limited with MSSyst.Drawing.Size;
limited with MSSyst.EventArgs;
limited with MSSyst.EventHandler;
limited with MSSyst.Guid;
limited with MSSyst.IAsyncResult;
with MSSyst.IDisposable;
with MSSyst.MarshalByRefObject;
limited with MSSyst.Runtime.Remoting.ObjRef;
limited with MSSyst.String;
limited with MSSyst.Type_k;
limited with MSSyst.Windows.Forms.AccessibleObject;
limited with MSSyst.Windows.Forms.AccessibleRole;
limited with MSSyst.Windows.Forms.AnchorStyles;
limited with MSSyst.Windows.Forms.AutoScaleMode;
limited with MSSyst.Windows.Forms.AutoSizeMode;
limited with MSSyst.Windows.Forms.AutoValidate;
limited with MSSyst.Windows.Forms.BindingContext;
limited with MSSyst.Windows.Forms.BoundsSpecified;
with MSSyst.Windows.Forms.ContainerControl;
limited with MSSyst.Windows.Forms.ContextMenuStrip;
limited with MSSyst.Windows.Forms.ContextMenu;
with MSSyst.Windows.Forms.Control;
limited with MSSyst.Windows.Forms.Control.ControlCollection;
limited with MSSyst.Windows.Forms.ControlBindingsCollection;
limited with MSSyst.Windows.Forms.ControlEventHandler;
limited with MSSyst.Windows.Forms.Cursor;
limited with MSSyst.Windows.Forms.DialogResult;
limited with MSSyst.Windows.Forms.DockStyle;
limited with MSSyst.Windows.Forms.DragDropEffects;
limited with MSSyst.Windows.Forms.DragEventHandler;
with MSSyst.Windows.Forms.Form;
limited with MSSyst.Windows.Forms.FormBorderStyle;
limited with MSSyst.Windows.Forms.FormClosedEventHandler;
limited with MSSyst.Windows.Forms.FormClosingEventHandler;
limited with MSSyst.Windows.Forms.FormStartPosition;
limited with MSSyst.Windows.Forms.FormWindowState;
limited with MSSyst.Windows.Forms.GetChildAtPointSkip;
limited with MSSyst.Windows.Forms.GiveFeedbackEventHandler;
limited with MSSyst.Windows.Forms.HScrollProperties;
limited with MSSyst.Windows.Forms.HelpEventHandler;
with MSSyst.Windows.Forms.IBindableComponent;
limited with MSSyst.Windows.Forms.IButtonControl;
with MSSyst.Windows.Forms.IContainerControl;
with MSSyst.Windows.Forms.IDropTarget;
with MSSyst.Windows.Forms.IWin32Window;
limited with MSSyst.Windows.Forms.IWindowTarget;
limited with MSSyst.Windows.Forms.ImageLayout;
limited with MSSyst.Windows.Forms.ImeMode;
limited with MSSyst.Windows.Forms.InputLanguageChangedEventHandler;
limited with MSSyst.Windows.Forms.InputLanguageChangingEventHandler;
limited with MSSyst.Windows.Forms.InvalidateEventHandler;
limited with MSSyst.Windows.Forms.KeyEventArgs;
limited with MSSyst.Windows.Forms.KeyEventHandler;
limited with MSSyst.Windows.Forms.KeyPressEventHandler;
limited with MSSyst.Windows.Forms.Layout.LayoutEngine;
limited with MSSyst.Windows.Forms.LayoutEventHandler;
limited with MSSyst.Windows.Forms.MainMenu;
limited with MSSyst.Windows.Forms.MdiLayout;
limited with MSSyst.Windows.Forms.MenuItem;
limited with MSSyst.Windows.Forms.MenuStrip;
with MSSyst.Windows.Forms.Message;
limited with MSSyst.Windows.Forms.MessageBoxIcon;
limited with MSSyst.Windows.Forms.MouseEventHandler;
limited with MSSyst.Windows.Forms.Padding;
limited with MSSyst.Windows.Forms.PaintEventHandler;
limited with MSSyst.Windows.Forms.Panel;
limited with MSSyst.Windows.Forms.PreProcessControlState;
limited with MSSyst.Windows.Forms.PreviewKeyDownEventHandler;
limited with MSSyst.Windows.Forms.QueryAccessibilityHelpEventHandler;
limited with MSSyst.Windows.Forms.QueryContinueDragEventHandler;
limited with MSSyst.Windows.Forms.RightToLeft;
limited with MSSyst.Windows.Forms.ScrollEventHandler;
with MSSyst.Windows.Forms.ScrollableControl;
limited with MSSyst.Windows.Forms.ScrollableControl.DockPaddingEdges;
limited with MSSyst.Windows.Forms.SizeGripStyle;
limited with MSSyst.Windows.Forms.TabControl;
limited with MSSyst.Windows.Forms.TabPage;
limited with MSSyst.Windows.Forms.ToolBarButton;
limited with MSSyst.Windows.Forms.ToolTip;
limited with MSSyst.Windows.Forms.UICuesEventHandler;
limited with MSSyst.Windows.Forms.VScrollProperties;
limited with MSSyst.Windows.Forms.ValidationConstraints;
limited with raptor.Buffered;
limited with raptor.ClassTabPage;
limited with raptor.CommentBox;
limited with raptor.Component;
limited with raptor.MasterConsole;
limited with raptor.Oval;
limited with raptor.Subchart;
limited with raptor.Visual_Flow_Form.Load_Delegate_Type;
limited with raptor.Visual_Flow_Form.MessageBox_Delegate_Type;
limited with raptor.Visual_Flow_Form.Set_Current_Tab_Delegate_Type;
limited with raptor.Visual_Flow_Form.Set_Running_Delegate_Type;
limited with raptor.Visual_Flow_Form.Set_TopMost_Delegate_Type;
limited with raptor.Visual_Flow_Form.Start_Delegate_Type;
limited with raptor.Visual_Flow_Form.invalidateScreen_Delegate_Type;
limited with raptor.Visual_Flow_Form.updateScreen_Delegate_Type;
limited with raptor.logging_info;
package raptor.Visual_Flow_Form is
   type Typ is new MSSyst.Windows.Forms.Form.Typ
         and MSSyst.ComponentModel.IComponent.Typ
         and MSSyst.IDisposable.Typ
         and MSSyst.Windows.Forms.IDropTarget.Typ
         and MSSyst.ComponentModel.ISynchronizeInvoke.Typ
         and MSSyst.Windows.Forms.IWin32Window.Typ
         and MSSyst.Windows.Forms.IBindableComponent.Typ
         and MSSyst.Windows.Forms.IContainerControl.Typ
   with record
      tooltip_text : access MSSyst.String.Typ'Class;
      pragma Import(MSIL,tooltip_text,"tooltip_text");
      scale : Float;
      pragma Import(MSIL,scale,"scale");
      print_scale : Float;
      pragma Import(MSIL,print_scale,"print_scale");
      log : access raptor.logging_info.Typ'Class;
      pragma Import(MSIL,log,"log");
      control_figure_selected : Integer;
      pragma Import(MSIL,control_figure_selected,"control_figure_selected");
      mouse_x : Integer;
      pragma Import(MSIL,mouse_x,"mouse_x");
      mouse_y : Integer;
      pragma Import(MSIL,mouse_y,"mouse_y");
      full_speed : Standard.Boolean;
      pragma Import(MSIL,full_speed,"full_speed");
      currentObj : access raptor.Component.Typ'Class;
      pragma Import(MSIL,currentObj,"currentObj");
      modified : Standard.Boolean;
      pragma Import(MSIL,modified,"modified");
      clipboard : access raptor.Component.Typ'Class;
      pragma Import(MSIL,clipboard,"clipboard");
      MC : access raptor.MasterConsole.Typ'Class;
      pragma Import(MSIL,MC,"MC");
      continuous_Run : Standard.Boolean;
      pragma Import(MSIL,continuous_Run,"continuous_Run");
      toolTip1 : access MSSyst.Windows.Forms.ToolTip.Typ'Class;
      pragma Import(MSIL,toolTip1,"toolTip1");
      undoButton : access MSSyst.Windows.Forms.ToolBarButton.Typ'Class;
      pragma Import(MSIL,undoButton,"undoButton");
      redoButton : access MSSyst.Windows.Forms.ToolBarButton.Typ'Class;
      pragma Import(MSIL,redoButton,"redoButton");
      menuMRU1 : access MSSyst.Windows.Forms.MenuItem.Typ'Class;
      pragma Import(MSIL,menuMRU1,"menuMRU1");
      menuMRU2 : access MSSyst.Windows.Forms.MenuItem.Typ'Class;
      pragma Import(MSIL,menuMRU2,"menuMRU2");
      menuMRU3 : access MSSyst.Windows.Forms.MenuItem.Typ'Class;
      pragma Import(MSIL,menuMRU3,"menuMRU3");
      menuMRU4 : access MSSyst.Windows.Forms.MenuItem.Typ'Class;
      pragma Import(MSIL,menuMRU4,"menuMRU4");
      contextMenu1 : access MSSyst.Windows.Forms.ContextMenu.Typ'Class;
      pragma Import(MSIL,contextMenu1,"contextMenu1");
      menuItemUndo : access MSSyst.Windows.Forms.MenuItem.Typ'Class;
      pragma Import(MSIL,menuItemUndo,"menuItemUndo");
      menuItemRedo : access MSSyst.Windows.Forms.MenuItem.Typ'Class;
      pragma Import(MSIL,menuItemRedo,"menuItemRedo");
      contextMenuInsert : access MSSyst.Windows.Forms.ContextMenu.Typ'Class;
      pragma Import(MSIL,contextMenuInsert,"contextMenuInsert");
      contextMenu2Paste : access MSSyst.Windows.Forms.MenuItem.Typ'Class;
      pragma Import(MSIL,contextMenu2Paste,"contextMenu2Paste");
      contextMenu2 : access MSSyst.Windows.Forms.ContextMenu.Typ'Class;
      pragma Import(MSIL,contextMenu2,"contextMenu2");
      carlisle : access MSSyst.Windows.Forms.TabControl.Typ'Class;
      pragma Import(MSIL,carlisle,"carlisle");
      menuItemGenerate : access MSSyst.Windows.Forms.MenuItem.Typ'Class;
      pragma Import(MSIL,menuItemGenerate,"menuItemGenerate");
      menuItemInkOff : access MSSyst.Windows.Forms.MenuItem.Typ'Class;
      pragma Import(MSIL,menuItemInkOff,"menuItemInkOff");
      menuItemInkBlack : access MSSyst.Windows.Forms.MenuItem.Typ'Class;
      pragma Import(MSIL,menuItemInkBlack,"menuItemInkBlack");
      menuItemInkBlue : access MSSyst.Windows.Forms.MenuItem.Typ'Class;
      pragma Import(MSIL,menuItemInkBlue,"menuItemInkBlue");
      menuItemInkRed : access MSSyst.Windows.Forms.MenuItem.Typ'Class;
      pragma Import(MSIL,menuItemInkRed,"menuItemInkRed");
      menuItemInkErase : access MSSyst.Windows.Forms.MenuItem.Typ'Class;
      pragma Import(MSIL,menuItemInkErase,"menuItemInkErase");
      menuItemInkGreen : access MSSyst.Windows.Forms.MenuItem.Typ'Class;
      pragma Import(MSIL,menuItemInkGreen,"menuItemInkGreen");
      menuItemInkSelect : access MSSyst.Windows.Forms.MenuItem.Typ'Class;
      pragma Import(MSIL,menuItemInkSelect,"menuItemInkSelect");
      menuMRU5 : access MSSyst.Windows.Forms.MenuItem.Typ'Class;
      pragma Import(MSIL,menuMRU5,"menuMRU5");
      menuMRU6 : access MSSyst.Windows.Forms.MenuItem.Typ'Class;
      pragma Import(MSIL,menuMRU6,"menuMRU6");
      menuMRU7 : access MSSyst.Windows.Forms.MenuItem.Typ'Class;
      pragma Import(MSIL,menuMRU7,"menuMRU7");
      menuMRU8 : access MSSyst.Windows.Forms.MenuItem.Typ'Class;
      pragma Import(MSIL,menuMRU8,"menuMRU8");
      menuMRU9 : access MSSyst.Windows.Forms.MenuItem.Typ'Class;
      pragma Import(MSIL,menuMRU9,"menuMRU9");
   end record;
   command_line_run : Standard.Boolean;
   pragma Import(MSIL,command_line_run,"command_line_run");
   command_line_input_redirect : Standard.Boolean;
   pragma Import(MSIL,command_line_input_redirect,"command_line_input_redirect");
   command_line_output_redirect : Standard.Boolean;
   pragma Import(MSIL,command_line_output_redirect,"command_line_output_redirect");
   Start_delegate : access raptor.Visual_Flow_Form.Start_Delegate_Type.Typ'Class;
   pragma Import(MSIL,Start_delegate,"Start_delegate");
   Set_Current_Tab_delegate : access raptor.Visual_Flow_Form.Set_Current_Tab_Delegate_Type.Typ'Class;
   pragma Import(MSIL,Set_Current_Tab_delegate,"Set_Current_Tab_delegate");
   Set_Running_delegate : access raptor.Visual_Flow_Form.Set_Running_Delegate_Type.Typ'Class;
   pragma Import(MSIL,Set_Running_delegate,"Set_Running_delegate");
   Set_TopMost_delegate : access raptor.Visual_Flow_Form.Set_TopMost_Delegate_Type.Typ'Class;
   pragma Import(MSIL,Set_TopMost_delegate,"Set_TopMost_delegate");
   MessageBox_delegate : access raptor.Visual_Flow_Form.MessageBox_Delegate_Type.Typ'Class;
   pragma Import(MSIL,MessageBox_delegate,"MessageBox_delegate");
   updateScreen_delegate : access raptor.Visual_Flow_Form.updateScreen_Delegate_Type.Typ'Class;
   pragma Import(MSIL,updateScreen_delegate,"updateScreen_delegate");
   invalidateScreen_delegate : access raptor.Visual_Flow_Form.invalidateScreen_Delegate_Type.Typ'Class;
   pragma Import(MSIL,invalidateScreen_delegate,"invalidateScreen_delegate");
   Load_delegate : access raptor.Visual_Flow_Form.Load_Delegate_Type.Typ'Class;
   pragma Import(MSIL,Load_delegate,"Load_delegate");
   assignment_fig : Integer;
   pragma Import(MSIL,assignment_fig,"assignment_fig");
   call_fig : Integer;
   pragma Import(MSIL,call_fig,"call_fig");
   input_fig : Integer;
   pragma Import(MSIL,input_fig,"input_fig");
   output_fig : Integer;
   pragma Import(MSIL,output_fig,"output_fig");
   if_control_fig : Integer;
   pragma Import(MSIL,if_control_fig,"if_control_fig");
   loop_fig : Integer;
   pragma Import(MSIL,loop_fig,"loop_fig");
   return_fig : Integer;
   pragma Import(MSIL,return_fig,"return_fig");
   flow_height : Integer;
   pragma Import(MSIL,flow_height,"flow_height");
   flow_width : Integer;
   pragma Import(MSIL,flow_width,"flow_width");
   control_height : Integer;
   pragma Import(MSIL,control_height,"control_height");
   control_width : Integer;
   pragma Import(MSIL,control_width,"control_width");
   control_X : Integer;
   pragma Import(MSIL,control_X,"control_X");
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function new_Visual_Flow_Form(
      This : Ref := null;
      dummy : access MSSyst.Object.Typ'Class) return Ref;
   function new_Visual_Flow_Form(
      This : Ref := null;
      silent : Standard.Boolean) return Ref;
   procedure AES_Decrypt(
      This : access Typ;
      input_file : access MSSyst.String.Typ'Class;
      output_file : access MSSyst.String.Typ'Class;
      hex_aes_key : access MSSyst.String.Typ'Class);
   procedure AES_KeyHint(
      This : access Typ;
      input_file : access MSSyst.String.Typ'Class);
   procedure Clear_Undo(
      This : access Typ);
   procedure Create_Control_graphx(
      This : access Typ);
   procedure Create_Flow_graphx(
      This : access Typ);
   function currentClass(
      This : access Typ) return access raptor.ClassTabPage.Typ'Class;
   procedure Cut_Click(
      This : access Typ;
      sender : access MSSyst.Object.Typ'Class;
      e : access MSSyst.EventArgs.Typ'Class);
   function Find_Tab(
      This : access Typ;
      s : access MSSyst.String.Typ'Class) return access raptor.Subchart.Typ'Class;
   function Get_Autosave_Name(
      This : access Typ) return access MSSyst.String.Typ'Class;
   function get_Breakpoint_Selection(
      This : access Typ) return access raptor.Component.Typ'Class;
   function get_Current_Selection(
      This : access Typ) return access raptor.Component.Typ'Class;
   function get_file_guid(
      This : access Typ) return MSSyst.Guid.Valuetype;
   function get_flow_panel(
      This : access Typ) return access raptor.Buffered.Typ'Class;
   function get_mainIndex(
      This : access Typ) return Integer;
   function get_panel1(
      This : access Typ) return access MSSyst.Windows.Forms.Panel.Typ'Class;
   function get_region_selected(
      This : access Typ) return Standard.Boolean;
   function get_runningState(
      This : access Typ) return Standard.Boolean;
   function get_scroll_location(
      This : access Typ) return MSSyst.Drawing.Point.Valuetype;
   function get_selectedComment(
      This : access Typ) return access raptor.CommentBox.Typ'Class;
   procedure handle_click(
      This : access Typ;
      sender : access MSSyst.Object.Typ'Class;
      e : access MSSyst.EventArgs.Typ'Class);
   procedure invalidateScreen(
      f : access raptor.Visual_Flow_Form.Typ'Class);
   function Is_Subchart_Call(
      This : access Typ;
      s : access MSSyst.String.Typ'Class) return Standard.Boolean;
   function Is_Subchart_Name(
      This : access Typ;
      s : access MSSyst.String.Typ'Class) return Standard.Boolean;
   procedure Load_Delegate(
      f : access raptor.Visual_Flow_Form.Typ'Class);
   procedure Load_MRU(
      This : access Typ;
      name : access MSSyst.String.Typ'Class);
   function mainSubchart(
      This : access Typ) return access raptor.Subchart.Typ'Class;
   procedure Make_Undoable(
      This : access Typ);
   procedure menuCountSymbols_Click(
      This : access Typ;
      sender : access MSSyst.Object.Typ'Class;
      e : access MSSyst.EventArgs.Typ'Class);
   procedure menuItemAssignment_Click(
      This : access Typ;
      sender : access MSSyst.Object.Typ'Class;
      e : access MSSyst.EventArgs.Typ'Class);
   procedure menuItemCall_Click(
      This : access Typ;
      sender : access MSSyst.Object.Typ'Class;
      e : access MSSyst.EventArgs.Typ'Class);
   procedure menuItemIf_Click(
      This : access Typ;
      sender : access MSSyst.Object.Typ'Class;
      e : access MSSyst.EventArgs.Typ'Class);
   procedure menuItemLoop_Click(
      This : access Typ;
      sender : access MSSyst.Object.Typ'Class;
      e : access MSSyst.EventArgs.Typ'Class);
   procedure menuItemOutput_Click(
      This : access Typ;
      sender : access MSSyst.Object.Typ'Class;
      e : access MSSyst.EventArgs.Typ'Class);
   procedure menuItemParallelogram_Click(
      This : access Typ;
      sender : access MSSyst.Object.Typ'Class;
      e : access MSSyst.EventArgs.Typ'Class);
   procedure menuItemReturn_Click(
      This : access Typ;
      sender : access MSSyst.Object.Typ'Class;
      e : access MSSyst.EventArgs.Typ'Class);
   procedure menuRenameSubchart_Click(
      This : access Typ;
      sender : access MSSyst.Object.Typ'Class;
      e : access MSSyst.EventArgs.Typ'Class);
   procedure MessageBox_Delegate(
      f : access raptor.Visual_Flow_Form.Typ'Class;
      text : access MSSyst.String.Typ'Class;
      caption : access MSSyst.String.Typ'Class;
      icon : MSSyst.Windows.Forms.MessageBoxIcon.Valuetype);
   procedure my_layout(
      This : access Typ);
   procedure new_clicked(
      This : access Typ;
      sender : access MSSyst.Object.Typ'Class;
      e : access MSSyst.EventArgs.Typ'Class);
   procedure num_horizontal_print_pages(
      This : access Typ;
      e : access MSSyst.Drawing.Printing.PrintPageEventArgs.Typ'Class;
      current_tab_start : access raptor.Oval.Typ'Class);
   procedure num_vertical_print_pages(
      This : access Typ;
      e : access MSSyst.Drawing.Printing.PrintPageEventArgs.Typ'Class;
      current_tab_start : access raptor.Oval.Typ'Class);
   procedure paste_Click(
      This : access Typ;
      sender : access MSSyst.Object.Typ'Class;
      e : access MSSyst.EventArgs.Typ'Class);
   procedure Perform_Autosave(
      This : access Typ);
   procedure Possible_Tab_Update(
      This : access Typ;
      tb : access MSSyst.Windows.Forms.TabPage.Typ'Class);
   procedure Rename_Tab(
      This : access Typ;
      old_name : access MSSyst.String.Typ'Class;
      name : access MSSyst.String.Typ'Class);
   function selectedTabMaybeNull(
      This : access Typ) return access raptor.Subchart.Typ'Class;
   procedure set_Breakpoint_Selection(
      This : access Typ;
      value : access raptor.Component.Typ'Class);
   procedure set_Current_Selection(
      This : access Typ;
      value : access raptor.Component.Typ'Class);
   procedure Set_Current_Tab_Delegate(
      f : access raptor.Visual_Flow_Form.Typ'Class;
      tb : access MSSyst.Windows.Forms.TabPage.Typ'Class);
   procedure set_file_guid(
      This : access Typ;
      value : MSSyst.Guid.Valuetype);
   procedure set_region_selected(
      This : access Typ;
      value : Standard.Boolean);
   procedure Set_Running_Delegate(
      f : access raptor.Visual_Flow_Form.Typ'Class;
      v : Standard.Boolean);
   procedure set_runningState(
      This : access Typ;
      value : Standard.Boolean);
   procedure set_scroll_location(
      This : access Typ;
      value : MSSyst.Drawing.Point.Valuetype);
   procedure set_selectedComment(
      This : access Typ;
      value : access raptor.CommentBox.Typ'Class);
   procedure Set_TopMost_Delegate(
      f : access raptor.Visual_Flow_Form.Typ'Class;
      v : Standard.Boolean);
   procedure Show_Text_On_Error(
      This : access Typ);
   function Start_Delegate(
      f : access raptor.Visual_Flow_Form.Typ'Class) return access raptor.Oval.Typ'Class;
   procedure Undo_Click(
      This : access Typ;
      sender : access MSSyst.Object.Typ'Class;
      e : access MSSyst.EventArgs.Typ'Class);
   procedure updateScreen(
      f : access raptor.Visual_Flow_Form.Typ'Class);
   procedure Visual_Flow_Form_KeyDown(
      This : access Typ;
      sender : access MSSyst.Object.Typ'Class;
      e : access MSSyst.Windows.Forms.KeyEventArgs.Typ'Class);
private
   pragma Convention(MSIL,Typ);
   pragma MSIL_Constructor(new_Visual_Flow_Form);
   pragma Import(MSIL,AES_Decrypt,"AES_Decrypt");
   pragma Import(MSIL,AES_KeyHint,"AES_KeyHint");
   pragma Import(MSIL,Clear_Undo,"Clear_Undo");
   pragma Import(MSIL,Create_Control_graphx,"Create_Control_graphx");
   pragma Import(MSIL,Create_Flow_graphx,"Create_Flow_graphx");
   pragma Import(MSIL,currentClass,"currentClass");
   pragma Import(MSIL,Cut_Click,"Cut_Click");
   pragma Import(MSIL,Find_Tab,"Find_Tab");
   pragma Import(MSIL,Get_Autosave_Name,"Get_Autosave_Name");
   pragma Import(MSIL,get_Breakpoint_Selection,"get_Breakpoint_Selection");
   pragma Import(MSIL,get_Current_Selection,"get_Current_Selection");
   pragma Import(MSIL,get_file_guid,"get_file_guid");
   pragma Import(MSIL,get_flow_panel,"get_flow_panel");
   pragma Import(MSIL,get_mainIndex,"get_mainIndex");
   pragma Import(MSIL,get_panel1,"get_panel1");
   pragma Import(MSIL,get_region_selected,"get_region_selected");
   pragma Import(MSIL,get_runningState,"get_runningState");
   pragma Import(MSIL,get_scroll_location,"get_scroll_location");
   pragma Import(MSIL,get_selectedComment,"get_selectedComment");
   pragma Import(MSIL,handle_click,"handle_click");
   pragma Import(MSIL,invalidateScreen,"invalidateScreen");
   pragma Import(MSIL,Is_Subchart_Call,"Is_Subchart_Call");
   pragma Import(MSIL,Is_Subchart_Name,"Is_Subchart_Name");
   pragma Import(MSIL,Load_Delegate,"Load_Delegate");
   pragma Import(MSIL,Load_MRU,"Load_MRU");
   pragma Import(MSIL,mainSubchart,"mainSubchart");
   pragma Import(MSIL,Make_Undoable,"Make_Undoable");
   pragma Import(MSIL,menuCountSymbols_Click,"menuCountSymbols_Click");
   pragma Import(MSIL,menuItemAssignment_Click,"menuItemAssignment_Click");
   pragma Import(MSIL,menuItemCall_Click,"menuItemCall_Click");
   pragma Import(MSIL,menuItemIf_Click,"menuItemIf_Click");
   pragma Import(MSIL,menuItemLoop_Click,"menuItemLoop_Click");
   pragma Import(MSIL,menuItemOutput_Click,"menuItemOutput_Click");
   pragma Import(MSIL,menuItemParallelogram_Click,"menuItemParallelogram_Click");
   pragma Import(MSIL,menuItemReturn_Click,"menuItemReturn_Click");
   pragma Import(MSIL,menuRenameSubchart_Click,"menuRenameSubchart_Click");
   pragma Import(MSIL,MessageBox_Delegate,"MessageBox_Delegate");
   pragma Import(MSIL,my_layout,"my_layout");
   pragma Import(MSIL,new_clicked,"new_clicked");
   pragma Import(MSIL,num_horizontal_print_pages,"num_horizontal_print_pages");
   pragma Import(MSIL,num_vertical_print_pages,"num_vertical_print_pages");
   pragma Import(MSIL,paste_Click,"paste_Click");
   pragma Import(MSIL,Perform_Autosave,"Perform_Autosave");
   pragma Import(MSIL,Possible_Tab_Update,"Possible_Tab_Update");
   pragma Import(MSIL,Rename_Tab,"Rename_Tab");
   pragma Import(MSIL,selectedTabMaybeNull,"selectedTabMaybeNull");
   pragma Import(MSIL,set_Breakpoint_Selection,"set_Breakpoint_Selection");
   pragma Import(MSIL,set_Current_Selection,"set_Current_Selection");
   pragma Import(MSIL,Set_Current_Tab_Delegate,"Set_Current_Tab_Delegate");
   pragma Import(MSIL,set_file_guid,"set_file_guid");
   pragma Import(MSIL,set_region_selected,"set_region_selected");
   pragma Import(MSIL,Set_Running_Delegate,"Set_Running_Delegate");
   pragma Import(MSIL,set_runningState,"set_runningState");
   pragma Import(MSIL,set_scroll_location,"set_scroll_location");
   pragma Import(MSIL,set_selectedComment,"set_selectedComment");
   pragma Import(MSIL,Set_TopMost_Delegate,"Set_TopMost_Delegate");
   pragma Import(MSIL,Show_Text_On_Error,"Show_Text_On_Error");
   pragma Import(MSIL,Start_Delegate,"Start_Delegate");
   pragma Import(MSIL,Undo_Click,"Undo_Click");
   pragma Import(MSIL,updateScreen,"updateScreen");
   pragma Import(MSIL,Visual_Flow_Form_KeyDown,"Visual_Flow_Form_KeyDown");
end raptor.Visual_Flow_Form;
pragma Import(MSIL,raptor.Visual_Flow_Form,
   ".ver 4:0:5:2",
   "[raptor]raptor.Visual_Flow_Form");
