-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
limited with MSSyst.Drawing.Drawing2D.GraphicsPath;
limited with MSSyst.Drawing.Graphics;
limited with MSSyst.String;
limited with MSSyst.Type_k;
package raptor.StopSign is
   type Typ is new MSSyst.Object.Typ   with record
      null;
   end record;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function new_StopSign(
      This : Ref := null) return Ref;
   procedure Draw(
      gr : access MSSyst.Drawing.Graphics.Typ'Class;
      x : Integer;
      y : Integer;
      size : Integer);
   function Make_Path(
      x : Integer;
      y : Integer;
      size : Integer) return access MSSyst.Drawing.Drawing2D.GraphicsPath.Typ'Class;
private
   pragma Convention(MSIL,Typ);
   pragma MSIL_Constructor(new_StopSign);
   pragma Import(MSIL,Draw,"Draw");
   pragma Import(MSIL,Make_Path,"Make_Path");
end raptor.StopSign;
pragma Import(MSIL,raptor.StopSign,
   ".ver 4:0:5:2",
   "[raptor]raptor.StopSign");
