-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
limited with MSSyst.String;
limited with MSSyst.Type_k;
with parse_tree;
limited with raptor.Component;
limited with raptor.Subchart;
package raptor.Step_Helpers is
   type Typ is new MSSyst.Object.Typ   with record
      null;
   end record;
   call_rect : access raptor.Component.Typ'Class;
   pragma Import(MSIL,call_rect,"call_rect");
   end_oval : access raptor.Component.Typ'Class;
   pragma Import(MSIL,end_oval,"end_oval");
   next_chart : access raptor.Subchart.Typ'Class;
   pragma Import(MSIL,next_chart,"next_chart");
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function new_Step_Helpers(
      This : Ref := null) return Ref;
   function Am_Leaving return Standard.Boolean;
   function Find_Successor(
      c : access raptor.Component.Typ'Class) return access raptor.Component.Typ'Class;
   function Invoke_Constructor(
      name : access MSSyst.String.Typ'Class;
      parameters : access parse_tree.parameter_list'Class) return Standard.Boolean;
   procedure Invoke_Method(
      name : access MSSyst.String.Typ'Class;
      parameters : access parse_tree.parameter_list'Class);
   procedure Invoke_Super_Constructor(
      parameters : access parse_tree.parameter_list'Class);
   procedure Invoke_Tab_Procedure(
      name : access MSSyst.String.Typ'Class;
      parameters : access parse_tree.parameter_list'Class);
   procedure Invoke_This_Constructor(
      parameters : access parse_tree.parameter_list'Class);
   procedure Set_State_Entering;
   procedure Set_State_Leaving;
private
   pragma Convention(MSIL,Typ);
   pragma MSIL_Constructor(new_Step_Helpers);
   pragma Import(MSIL,Am_Leaving,"Am_Leaving");
   pragma Import(MSIL,Find_Successor,"Find_Successor");
   pragma Import(MSIL,Invoke_Constructor,"Invoke_Constructor");
   pragma Import(MSIL,Invoke_Method,"Invoke_Method");
   pragma Import(MSIL,Invoke_Super_Constructor,"Invoke_Super_Constructor");
   pragma Import(MSIL,Invoke_Tab_Procedure,"Invoke_Tab_Procedure");
   pragma Import(MSIL,Invoke_This_Constructor,"Invoke_This_Constructor");
   pragma Import(MSIL,Set_State_Entering,"Set_State_Entering");
   pragma Import(MSIL,Set_State_Leaving,"Set_State_Leaving");
end raptor.Step_Helpers;
pragma Import(MSIL,raptor.Step_Helpers,
   ".ver 4:0:5:2",
   "[raptor]raptor.Step_Helpers");
