-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
limited with MSSyst.ComponentModel.CancelEventHandler;
with MSSyst.ComponentModel.Component;
with MSSyst.ComponentModel.IComponent;
limited with MSSyst.ComponentModel.IContainer;
limited with MSSyst.ComponentModel.ISite;
with MSSyst.ComponentModel.ISynchronizeInvoke;
limited with MSSyst.Delegate;
limited with MSSyst.Drawing.Bitmap;
limited with MSSyst.Drawing.Color;
limited with MSSyst.Drawing.Font;
limited with MSSyst.Drawing.Graphics;
limited with MSSyst.Drawing.Icon;
limited with MSSyst.Drawing.Image;
limited with MSSyst.Drawing.Point;
limited with MSSyst.Drawing.Rectangle;
limited with MSSyst.Drawing.Region;
limited with MSSyst.Drawing.SizeF;
limited with MSSyst.Drawing.Size;
limited with MSSyst.EventArgs;
limited with MSSyst.EventHandler;
limited with MSSyst.IAsyncResult;
with MSSyst.IDisposable;
with MSSyst.MarshalByRefObject;
limited with MSSyst.Runtime.Remoting.ObjRef;
limited with MSSyst.String;
limited with MSSyst.Type_k;
limited with MSSyst.Windows.Forms.AccessibleObject;
limited with MSSyst.Windows.Forms.AccessibleRole;
limited with MSSyst.Windows.Forms.AnchorStyles;
limited with MSSyst.Windows.Forms.AutoScaleMode;
limited with MSSyst.Windows.Forms.AutoSizeMode;
limited with MSSyst.Windows.Forms.AutoValidate;
limited with MSSyst.Windows.Forms.BindingContext;
limited with MSSyst.Windows.Forms.BoundsSpecified;
with MSSyst.Windows.Forms.ContainerControl;
limited with MSSyst.Windows.Forms.ContextMenuStrip;
limited with MSSyst.Windows.Forms.ContextMenu;
with MSSyst.Windows.Forms.Control;
limited with MSSyst.Windows.Forms.Control.ControlCollection;
limited with MSSyst.Windows.Forms.ControlBindingsCollection;
limited with MSSyst.Windows.Forms.ControlEventHandler;
limited with MSSyst.Windows.Forms.Cursor;
limited with MSSyst.Windows.Forms.DialogResult;
limited with MSSyst.Windows.Forms.DockStyle;
limited with MSSyst.Windows.Forms.DragDropEffects;
limited with MSSyst.Windows.Forms.DragEventHandler;
with MSSyst.Windows.Forms.Form;
limited with MSSyst.Windows.Forms.FormBorderStyle;
limited with MSSyst.Windows.Forms.FormClosedEventHandler;
limited with MSSyst.Windows.Forms.FormClosingEventHandler;
limited with MSSyst.Windows.Forms.FormStartPosition;
limited with MSSyst.Windows.Forms.FormWindowState;
limited with MSSyst.Windows.Forms.GetChildAtPointSkip;
limited with MSSyst.Windows.Forms.GiveFeedbackEventHandler;
limited with MSSyst.Windows.Forms.HScrollProperties;
limited with MSSyst.Windows.Forms.HelpEventHandler;
with MSSyst.Windows.Forms.IBindableComponent;
limited with MSSyst.Windows.Forms.IButtonControl;
with MSSyst.Windows.Forms.IContainerControl;
with MSSyst.Windows.Forms.IDropTarget;
with MSSyst.Windows.Forms.IWin32Window;
limited with MSSyst.Windows.Forms.IWindowTarget;
limited with MSSyst.Windows.Forms.ImageLayout;
limited with MSSyst.Windows.Forms.ImeMode;
limited with MSSyst.Windows.Forms.InputLanguageChangedEventHandler;
limited with MSSyst.Windows.Forms.InputLanguageChangingEventHandler;
limited with MSSyst.Windows.Forms.InvalidateEventHandler;
limited with MSSyst.Windows.Forms.KeyEventHandler;
limited with MSSyst.Windows.Forms.KeyPressEventHandler;
limited with MSSyst.Windows.Forms.Layout.LayoutEngine;
limited with MSSyst.Windows.Forms.LayoutEventHandler;
limited with MSSyst.Windows.Forms.MainMenu;
limited with MSSyst.Windows.Forms.MdiLayout;
limited with MSSyst.Windows.Forms.MenuStrip;
with MSSyst.Windows.Forms.Message;
limited with MSSyst.Windows.Forms.MouseEventHandler;
limited with MSSyst.Windows.Forms.Padding;
limited with MSSyst.Windows.Forms.PaintEventHandler;
limited with MSSyst.Windows.Forms.PreProcessControlState;
limited with MSSyst.Windows.Forms.PreviewKeyDownEventHandler;
limited with MSSyst.Windows.Forms.QueryAccessibilityHelpEventHandler;
limited with MSSyst.Windows.Forms.QueryContinueDragEventHandler;
limited with MSSyst.Windows.Forms.RightToLeft;
limited with MSSyst.Windows.Forms.ScrollEventHandler;
with MSSyst.Windows.Forms.ScrollableControl;
limited with MSSyst.Windows.Forms.ScrollableControl.DockPaddingEdges;
limited with MSSyst.Windows.Forms.SizeGripStyle;
limited with MSSyst.Windows.Forms.UICuesEventHandler;
limited with MSSyst.Windows.Forms.VScrollProperties;
limited with MSSyst.Windows.Forms.ValidationConstraints;
limited with raptor.MasterConsole.clear_text_delegate_type;
limited with raptor.MasterConsole.set_text_delegate_type;
package raptor.MasterConsole is
   type Typ is new MSSyst.Windows.Forms.Form.Typ
         and MSSyst.ComponentModel.IComponent.Typ
         and MSSyst.IDisposable.Typ
         and MSSyst.Windows.Forms.IDropTarget.Typ
         and MSSyst.ComponentModel.ISynchronizeInvoke.Typ
         and MSSyst.Windows.Forms.IWin32Window.Typ
         and MSSyst.Windows.Forms.IBindableComponent.Typ
         and MSSyst.Windows.Forms.IContainerControl.Typ
   with record
      clear_text_Delegate : access raptor.MasterConsole.clear_text_delegate_type.Typ'Class;
      pragma Import(MSIL,clear_text_Delegate,"clear_text_Delegate");
      set_text_Delegate : access raptor.MasterConsole.set_text_delegate_type.Typ'Class;
      pragma Import(MSIL,set_text_Delegate,"set_text_Delegate");
   end record;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function new_MasterConsole(
      This : Ref := null) return Ref;
   function new_MasterConsole(
      This : Ref := null;
      standalone : Standard.Boolean) return Ref;
   procedure clear_text_delegate(
      mc : access raptor.MasterConsole.Typ'Class);
   procedure clear_txt(
      This : access Typ);
   procedure MasterConsole_Resize(
      This : access Typ;
      sender : access MSSyst.Object.Typ'Class;
      e : access MSSyst.EventArgs.Typ'Class);
   procedure menuArial_Click(
      This : access Typ;
      sender : access MSSyst.Object.Typ'Class;
      e : access MSSyst.EventArgs.Typ'Class);
   procedure menuCourier_Click(
      This : access Typ;
      sender : access MSSyst.Object.Typ'Class;
      e : access MSSyst.EventArgs.Typ'Class);
   procedure menuFont10_Click(
      This : access Typ;
      sender : access MSSyst.Object.Typ'Class;
      e : access MSSyst.EventArgs.Typ'Class);
   procedure menuFont12_Click(
      This : access Typ;
      sender : access MSSyst.Object.Typ'Class;
      e : access MSSyst.EventArgs.Typ'Class);
   procedure menuFont14_Click(
      This : access Typ;
      sender : access MSSyst.Object.Typ'Class;
      e : access MSSyst.EventArgs.Typ'Class);
   procedure menuFont16_Click(
      This : access Typ;
      sender : access MSSyst.Object.Typ'Class;
      e : access MSSyst.EventArgs.Typ'Class);
   procedure menuFont20_Click(
      This : access Typ;
      sender : access MSSyst.Object.Typ'Class;
      e : access MSSyst.EventArgs.Typ'Class);
   procedure menuFont24_Click(
      This : access Typ;
      sender : access MSSyst.Object.Typ'Class;
      e : access MSSyst.EventArgs.Typ'Class);
   procedure menuFont28_Click(
      This : access Typ;
      sender : access MSSyst.Object.Typ'Class;
      e : access MSSyst.EventArgs.Typ'Class);
   procedure menuFont36_Click(
      This : access Typ;
      sender : access MSSyst.Object.Typ'Class;
      e : access MSSyst.EventArgs.Typ'Class);
   procedure menuFont6_Click(
      This : access Typ;
      sender : access MSSyst.Object.Typ'Class;
      e : access MSSyst.EventArgs.Typ'Class);
   procedure menuFont8_Click(
      This : access Typ;
      sender : access MSSyst.Object.Typ'Class;
      e : access MSSyst.EventArgs.Typ'Class);
   procedure menuTimes_Click(
      This : access Typ;
      sender : access MSSyst.Object.Typ'Class;
      e : access MSSyst.EventArgs.Typ'Class);
   procedure program_stopped(
      This : access Typ;
      message : access MSSyst.String.Typ'Class);
   procedure Set_Font_Size(
      This : access Typ);
   procedure set_text(
      This : access Typ;
      text : access MSSyst.String.Typ'Class);
   procedure set_text_delegate(
      mc : access raptor.MasterConsole.Typ'Class;
      text : access MSSyst.String.Typ'Class);
private
   pragma Convention(MSIL,Typ);
   pragma MSIL_Constructor(new_MasterConsole);
   pragma Import(MSIL,clear_text_delegate,"clear_text_delegate");
   pragma Import(MSIL,clear_txt,"clear_txt");
   pragma Import(MSIL,MasterConsole_Resize,"MasterConsole_Resize");
   pragma Import(MSIL,menuArial_Click,"menuArial_Click");
   pragma Import(MSIL,menuCourier_Click,"menuCourier_Click");
   pragma Import(MSIL,menuFont10_Click,"menuFont10_Click");
   pragma Import(MSIL,menuFont12_Click,"menuFont12_Click");
   pragma Import(MSIL,menuFont14_Click,"menuFont14_Click");
   pragma Import(MSIL,menuFont16_Click,"menuFont16_Click");
   pragma Import(MSIL,menuFont20_Click,"menuFont20_Click");
   pragma Import(MSIL,menuFont24_Click,"menuFont24_Click");
   pragma Import(MSIL,menuFont28_Click,"menuFont28_Click");
   pragma Import(MSIL,menuFont36_Click,"menuFont36_Click");
   pragma Import(MSIL,menuFont6_Click,"menuFont6_Click");
   pragma Import(MSIL,menuFont8_Click,"menuFont8_Click");
   pragma Import(MSIL,menuTimes_Click,"menuTimes_Click");
   pragma Import(MSIL,program_stopped,"program_stopped");
   pragma Import(MSIL,Set_Font_Size,"Set_Font_Size");
   pragma Import(MSIL,set_text,"set_text");
   pragma Import(MSIL,set_text_delegate,"set_text_delegate");
end raptor.MasterConsole;
pragma Import(MSIL,raptor.MasterConsole,
   ".ver 4:0:5:2",
   "[raptor]raptor.MasterConsole");
