-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
limited with MSSyst.String;
limited with MSSyst.Type_k;
package raptor.Constructors is
   type Typ is new MSSyst.Object.Typ   with record
      null;
   end record;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function new_Constructors(
      This : Ref := null) return Ref;
   function Make_Strings(
      size : Integer) return access MSSyst.String.Ref_arr;
private
   pragma Convention(MSIL,Typ);
   pragma MSIL_Constructor(new_Constructors);
   pragma Import(MSIL,Make_Strings,"Make_Strings");
end raptor.Constructors;
pragma Import(MSIL,raptor.Constructors,
   ".ver 4:0:5:2",
   "[raptor]raptor.Constructors");
